mysite/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('todos/', include('todos.urls')),
    path('admin/', admin.site.urls),
]

todos/urls.py
from django.urls import path

from . import views

app_name = 'todos'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:todolist_id>/', views.detail, name='detail'),
    path('<int:todolist_id>/<int:todo_id>/', views.todo, name='todo'),
    path('create_todolist', views.create_todolist, name='create_todolist'),
    path('create_todo/<int:todolist_id>/', views.create_todo, name='create_todo')
]

todos/models.py
from django.db import models


class TodoList(models.Model):
    todolist_name = models.CharField(max_length=200)

    def __str__(self):
        return self.todolist_name


class Todo(models.Model):
    todo_list = models.ForeignKey(TodoList, on_delete=models.CASCADE)
    todo_text = models.CharField(max_length=200)
    is_checked = models.BooleanField(default=False)

    def __str__(self):
        return self.todo_text

todos/views.py
from django import template
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, response, HttpResponseRedirect
from django.template import loader
from django.http import Http404
from django.urls import reverse
from django.views import generic

from todos.models import TodoList, Todo

class IndexView(generic.ListView):
    template_name = 'todos/index.html'
    context_object_name = 'todolists_list'

    def get_queryset(self):
        return TodoList.objects.all()

def detail(request, todolist_id):
    todos_list = get_object_or_404(TodoList, pk=todolist_id)
    return render(request, 'todos/detail.html', {'todos_list':todos_list.todo_set.all(), 'todolist_id': todolist_id})

def todo(requse, todolist_id, todo_id):
    return HttpResponse(Todo.objects.get(pk=todo_id))

def create_todolist(request):
    try:
        todolist = TodoList(todolist_name=request.POST['todolist_name'])
    except KeyError:
        return HttpResponseRedirect(reverse('todos:index'))
    if todolist.todolist_name:
        todolist.save()
    return HttpResponseRedirect(reverse('todos:index'))

def create_todo(request, todolist_id):
    try:
        todolist = TodoList.objects.get(pk=todolist_id)
        todolist.todo_set.create(todo_text=request.POST['todo_text'])
    except KeyError:
        return HttpResponseRedirect(reverse('todos:detail', args=(todolist_id,)))
    return HttpResponseRedirect(reverse('todos:detail', args=(todolist_id,)))

todos/templates/todos/detail.html
{% if todos_list %}
    <ul>
    {% for todo in todos_list %}
        <li><a href="/todos/{{todolist_id}}/{{todo.id}}/"> {{ todo.todo_text }} </a> </li>
    {% endfor %}
    </ul>
{% else %}
    <p> No todos are available </p>
{% endif %}

<form action="{% url 'todos:create_todo' todolist_id %}", method="post"> 
    {% csrf_token %} 
    <input type="text" name="todo_text" id="todo_text_input" placeholder="Todo text..."/>
    <input type="submit" value="Create"/>
</form>

todos/templates/todos/index.html
{% if todolists_list %}
    <ul>
    {% for todolist in todolists_list %}
        <li><a href="{% url 'todos:detail' todolist.id %}"> {{ todolist.todolist_name }} </a> </li>
    {% endfor %}
    </ul>
{% else %}
    <p> No todolists are available </p>
{% endif %}

<form action="{% url 'todos:create_todolist' %}", method="post"> 
    {% csrf_token %} 
    <input type="text" name="todolist_name" id="todolist_name_input" placeholder="Todolist name..."/>
    <input type="submit" value="Create"/>
</form>